### ISSUE TITLE
[Android] Implement new Biometrics API

### ISSUE THREAD

**Issue by simonedavico** [SelfLender/react-native-biometrics#15]
Android SDK 28 [introduces a new Biometrics API](https://android-developers.googleblog.com/2018/06/better-biometrics-in-android-p.html) with a standard dialog prompt. 

It also features a [compat library](https://mvnrepository.com/artifact/androidx.biometric/biometric) for previous Android versions which is meant to offer a consistent experience.

I looked at the source code and it seems like it still uses the now deprecated `FingerprintManager`.

Would you be interested in replacing the old API with the new one?

**Comment by NappyPirate** [comment]
I have considered updating to the new Android SDK 28 biometrics API, but there are currently 2 concerns about upgrading:

1. The [compat library](https://mvnrepository.com/artifact/androidx.biometric/biometric) is currently only in alpha release, and I prefer not to release a version of this project that uses an alpha version of a compatibility library.

1. The new [BiometricPrompt API](https://developer.android.com/reference/android/hardware/biometrics/package-summary) actually removes functionality that I feel is necessary for creating a pleasant user experience.  Specifically, with the BiometricPrompt there is no way to detect the presence of hardware or if a user is enrolled in biometrics without trying to launch the prompt.  This loss of functionality would break the `isSensorAvailable` function in this library.  (it appears others are experiencing this frustration as well on [stackoverflow](https://stackoverflow.com/questions/50968732/determine-if-biometric-hardware-is-present-and-the-user-has-enrolled-biometrics) and [google issue tracker](https://issuetracker.google.com/issues/109826221))

Even given these concerns, I'm going to keep this issue open because hopefully something changes in the future and I can re-evaluate.

**Comment by cgomezmendez** [comment]
@NappyPirate What about having Biometric in a parallel version meanwhile?

**Comment by simonedavico** [comment]
Thank you for the feedback! Good to know, I was not aware of these issues
and I agree that they definitely block adoption of the new API. It is quite
frightening that the discussion on the Google issue tracker seems mostly
dead 😕

Il giorno mar 6 nov 2018, 21:52 Cristian Gomez <notifications@github.com>
ha scritto:

**Comment by NappyPirate** [comment]
Some good news on this issue.  It appears that google is addressing my concerns with their API in the Android Q API by adding a new [BiometricsManager](https://developer.android.com/reference/android/hardware/biometrics/BiometricManager.html).  I plan to investigate this further after Android Q officially releases.  As it stands today though, the [compat library](https://mvnrepository.com/artifact/androidx.biometric/biometric) is still in alpha.

**Comment by jakejarrett** [comment]
The compat library has reached `RC02` this week [https://mvnrepository.com/artifact/androidx.biometric/biometric/1.0.0-rc02](1.0.0-rc02).

Does 1.0 (rc or otherwise) contain the changes to support the new BiometricsManager?
