### ISSUE TITLE
isSensorAvailable() not properly working

### ISSUE THREAD

**Issue by strawberry-code** [SelfLender/react-native-biometrics#159]
I am using:

1. react-native v0.61.5
2. react-native-biometrics v2.1.4
3. Samsung Galaxy S20
4. Android 11

When the app code invokes `isSensorAvailable()` it returns following object:

```
{
    "available": false
    "biometryType": "undefined",
    "error": "BIOMETRIC_ERROR_NONE_ENROLLED"
}
```

However, with this device, I am able to use properly the Fingerprint in other apps and to unlock the device. My finger is set and enrolled in Fingerprints. What is happening?

**Comment by ch3tan03** [comment]
did you find any solution for this?

**Comment by strawberry-code** [comment]
Sorry, we have found no solutions.

**Comment by AngelTrinidad** [comment]
I have the same error on iPhone X physical device

**Comment by jayfunk** [comment]
Is there any information logged out in the app console or logcat you can provide? 

Have you attempted to test this on a different android device? 

There are some Samsung devices that were blacklisted by android due to weak security implementations. 

Would you be able to try this out with version 3.0.1 of the package?

**Comment by jayfunk** [comment]
I would suggest updating to the latest version and see if that resolves your issue.
