### ISSUE TITLE
[Question] What happens if user creates new fingerprint?

### ISSUE THREAD

**Issue by betoharres** [SelfLender/react-native-biometrics#16]
Sorry for posting questions here, but from what I understand in the README, this library creates a key pair and stores it on the phone, and just uses the fingerprint to access the private key, which could remain the same if the user changes the fingerprint, right?

nice work with the library btw, cheers 🍺

**Comment by betoharres** [comment]
Nvm, I just did the test and the pub key changes it, even though it was the same finger, I might have scanned better this time and generated a different keypair. 
One thing I noticed is that the pub key of the 2nd scan had very similar characters from my 1st scan.

**Comment by thecodecafe** [comment]
I'm currently working on an app but don't know if this will suffice, it's for SIM card registration, I want to be able to capture user fingerprint encrypt and store it in a DB but the problem is the library encrypts it for you and I'm not sure what will happen in a case where the user moved from iOS to Android or Android to iOS, the fingerprint won't be the same, which means I won't be able to go back to data I've saved before because before they can view that data or edit it, they will need to scan their fingerprint again.
