### ISSUE TITLE
Is this package still going to be maintained

### ISSUE THREAD

**Issue by EddyDunda** [SelfLender/react-native-biometrics#162]
I want to use this package, but i see that latest update was 1 year ago. Can i use it safely?

**Comment by NKGS** [comment]
Yes I too wanted to know the same.

**Comment by shokimble** [comment]
Just because a package doesn't have much or any activity doesn't mean it's not going to be maintained or fit for purpose. 

Most people working on packages volunteer their time so if there's no good reason to make an update or answer the 3000th question about usage or whether the package is still maintained then they likely won't.

Whether it's fit for purpose is up to you.

That being said I can vouch that it still works fine and there are no issues here.

**Comment by KonstantinZhukovskij** [comment]
Is there any news here? Maybe the author @SelfLender himself would answer at the expense of further support?

**Comment by kg-currenxie** [comment]
Still working fine here in production!

**Comment by hlynbech** [comment]
In my opinion, the problem is that there has actually only been one contributor on all the main releases, and no responses to any open issues or pull requests - even the most no-brainer fixes that should have been closed or merged a long time ago.
Now it's been two years with total radio silence from @NappyPirate and that's not a good sign.
If anybody know about or have made a fork with serious commitment to maintaining, could you post it here? That would be a big help.

**Comment by jayfunk** [comment]
@hlynbech @KonstantinZhukovskij Work is underway! Take a look at #183 for upcoming fixes and features.
