### ISSUE TITLE
_reactNativeBiometrics.default.isSensorAvailable is not a function

### ISSUE THREAD

**Issue by karthi238** [SelfLender/react-native-biometrics#191]
Hi 
Getting below error when I try to use any methods of react-native-biometrics.

_reactNativeBiometrics.default.isSensorAvailable is not a function.

I haven't updated the package, this error is coming all of a sudden. 

package version : 2.1.4
 react-native : ^0.62.2"
![Simulator Screen Shot - Iphone 13 Pro Max - 2022-06-15 at 09 59 22](https://user-images.githubusercontent.com/43806184/173736892-f3afa333-c931-4d3a-b5e4-412774547a27.png)

**Comment by cakesoft-shashank** [comment]
I am also getting the same error, did you fix it?

**Comment by karthi238** [comment]
Previously I was using like
ReactNativeBiometrics.isSensorAvailable() which is giving this error.

Fix
const RNBiometrics = new ReactNativeBiometrics()
RNBiometrics.isSensorAvailable()

This fixed the issue, but not sure why this is causing the issue suddenly

**Comment by jayfunk** [comment]
This is due to an issue with how I released the latest build. I should have released it as a major version update but instead released it as a minor version. The latest version, 2.2.0, includes a breaking API change. The default export is now a class to manage state related to passcode fallback. The original API is available as named exports.
