### ISSUE TITLE
Can not custom view on Android.

### ISSUE THREAD

**Issue by ATShiTou** [SelfLender/react-native-biometrics#2]
Why not a module without any dialogs on Android？The user interface can not custom.

**Comment by NappyPirate** [comment]
I decided to add a dialog for biometric authentication on Android to mimic the functionality of iOS, where a prompt is created by the OS itself for biometrics.  I also tried to follow this material design specification: https://material.io/guidelines/patterns/fingerprint.html to make the fingerprint prompt on Android feel more universal and system like.  

Ultimately, I wanted this library to be easy to use with little to no configuration and requiring almost no OS specific react native code.  I do not currently have any intention to remove the Android fingerprint dialog because we do not currently need that functionality.  However, if you want to create a pull request to make the Android fingerprint dialog configurable or optional, I will be happy to review it.

**Comment by ATShiTou** [comment]
I mean the dialog is so ugly that all designers in my team refuse it.
