### ISSUE TITLE
Having trouble verifying signature with public key on the NodeJS side

### ISSUE THREAD

**Issue by TheFirstJeffreyLee** [SelfLender/react-native-biometrics#32]
I saw this post already:
https://github.com/SelfLender/react-native-biometrics/issues/21

And their proposed solution was right here:
https://gist.github.com/lkdocs/6519372

I am using the `node-rsa` package right now to try to mimic what they are doing but I keep getting into this issue where it's like `invalid ASN1 Error`. Is there an example of this being done on the Node JS side?

I am getting that error on the first step of `importKey`:

```
const pubKey = `MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAynY5oEuJ0/qv3KPZWJdcfUGIIBNWq30NnUS201XyV4B1aP7lTO+TrlDiWsWLon+JDd5H30/NS0dihQoxWXgco4l1xiRotgaDT9p1FlVeNm/z49Ybb0zOxMhDy950Y4TwjyP03PJAV7FqdHbJNlTnmoWpHW8JdzJP4DfzXAQdnq9SIG+fARo+2W+NxTYpH2meby1PdrBjEAiqc/nguJj4u/RC2Utol+cGEZoSfSjuVzHLEcNpjYGXRi/432GpCgWeSTbft+qv3ei/R1GrLya8P5k2426w6eI1OPR4p/Cw+PwRcM+J28NMgH5pPwRWkVletGuivIwxzXgdDgYlHlRGewIDAQAB`
const key = new NodeRSA();
const signer = key.importKey(pubKey, ‘pkcs1-public-pem’);
```

**Comment by NappyPirate** [comment]
The public key is base64 encoded binary data, so the format is actually Binary DER-encoded format. You have to decode the public key before importing it and use the correct import format.  You will also need the payload message and the signature of the message in order to verify everything.  Here is an example:

```javascript
import NodeRSA from 'node-rsa'

const publicKey = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0ukwwhq00ZmVtY1dswdVUg0tDNAbPt/GCWRUua1zsmeKT90NP3rsAEbIHJ89mQJ5/fVrl+umS5uq3F7AdZNh2R269KLV2MSytoMWR2zLD4oVUdDSwbEu8h1cx8s8vk6QpjmvZkxXYWXM1kh+9AqEjsWL3gE5hShOaqf8zl1k9pjZVywndaFi7/SsvQGy6WlSZT7cPyF/xwxGOBe3h9nijlhCIpR9AkbTSsQrVRz+iudGLSuuzS09hgX6fdqcRqR+T2UocfGJrSAqBhHVPeCksQ/OgwGJtaZQde+Cu/9FGa9LAdRcMm/WUILLlv2Dn7DGjhe/S8xvsZh7p7ghYbgxwwIDAQAB'
const payload = 'some test payload'
const signature = 'DB1E4dSOoA9avqhR6I2vnQQJ4Ktptsq/Z89afh0tX9gcCfWzBnkBySaeY0MjIHTOUqKimbRfFxb4NDIBCgIu/bQufIrESIl8v/U6jHPleP5wn9fh+p02mvTKUSDU8p6zBygXiGUe2SWwHaGzYvHDIW1Rm6mL22kv1qTkMhRQsVsBAgVtn8vHx6yMvN+XmQAM0Z2BDecC2kyfjZrBkJT7stzHW/1fT4GiVmoC7haaR2JRdHlGWBZXktmUvqo8xEdgYyMq582Q6N+Jw6Ic7TQc+584yviSgB3fAg32b7z5NdRVAwS2FCbLkC7DQNn+WCBk6XHOwKuu1XR9eUWU+k0Qgg=='

const publicKeyBuffer = Buffer.from(publicKey, 'base64')
const key = new NodeRSA()
const signer = key.importKey(publicKeyBuffer, 'public-der')
const signatureVerified = signer.verify(Buffer.from(payload), signature, 'utf-8', 'base64')

console.log(signatureVerified)
```

**Comment by TheFirstJeffreyLee** [comment]
Wow that was really helpful. Thank you. One thing to help those who are going through the same problem but are using typescript. On the `verify` call it is 'utf8', no hyphen.

@NappyPirate I noticed you used 'public-der' when importing the public key. I get a typescript error when I do that because that isn't one of the formats. So I played around trying out pkcs1, component and pkcs8. The last one worked, but confused me. I don't see any mention of pkcs8 in this package and looking at the `createKeys` function, it seems to be using pkcs1 as well. So I guess my confusion is why do I still get this error on 'pkcs1-public-der' but not 'pkcs8-public-der'

**Comment by NappyPirate** [comment]
The typescript error you received is probably because typescript is not picking up the aliases that I found for formats in the `node-rsa` library here: https://github.com/rzcoder/node-rsa/blob/9feef4ba84eac4d4a62eb208c8792e37d272aee0/src/NodeRSA.js#L34

As for why pkcs1 does not work, it's because the public key format appears to actually be in pkcs8, which is essentially an evolution of the pkcs1 format and contains the same key encoding, but also includes data about the algorithm and the key.  This stackoverflow might help to explain: https://stackoverflow.com/questions/48958304/pkcs1-and-pkcs8-format-for-rsa-private-key

**Comment by eakenbor** [comment]
Hi @NappyPirate . Please do you know how I can verify the signature in a python backend?

**Comment by Navipro70** [comment]
@eakenbor 
https://stuvel.eu/python-rsa-doc/
