### ISSUE TITLE
Android X support ?

### ISSUE THREAD

**Issue by jinshin1013** [SelfLender/react-native-biometrics#37]
I am actually not entirely sure whether all the libraries need to opt into using AndroidX to support `react-native@0.60` nor how hard it is for a library to support it. I haven't got a chance to upgrade the project to use `react-native@0.60` to test out things but could you have a look into updating the library to use AndroidX?

**Comment by ASteinheiser** [comment]
I just tried to upgrade `react-native` to `0.60.5` and this package worked for iOS, however failed to build on Android, due to the lack of AndroidX support. I get the following errors:
`error: package android.support.annotation does not exist`
`error: cannot find symbol class Nullable`

After reading the [official release notes](https://facebook.github.io/react-native/blog/2019/07/03/version-60#androidx-support) on `0.60`, it appears that AndroidX support will need to be added by the maintainers as Android projects are either all or nothing for AndroidX support. So if a project expects things in AndroidX format, everything has to abide (unless using the current workaround of [jetifier](https://github.com/mikehardy/jetifier))

**Comment by jinshin1013** [comment]
I can confirm that simply adding `"postinstall": "npx jetify"` in `package.json` successfully convert `react-native-biometrics` to use `androidx` but ideally it should be supported from the library.

**Comment by NappyPirate** [comment]
This should be fixed in [1.7.0](https://github.com/SelfLender/react-native-biometrics/releases/tag/1.7.0)
