### ISSUE TITLE
"Fingerprint not recognized" Problem

### ISSUE THREAD

**Issue by claude39** [SelfLender/react-native-biometrics#6]
I can't set new biometric registry, I want to add new fingerprint but the input fingerprint only authorize the given fingerprint in the security. Which basically only allows the owner of the device to use it...

**Comment by NappyPirate** [comment]
This is the intended functionality.  That is how fingerprint authorization is handled by both iOS and Android.  Fingerprints are registered at the OS level, and apps can hook into the OS to prompt users for their already registered biometrics before allowing certain actions.  

Therefore I am closing this issue since it is the intended functionality.
